In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("archive.zip")

data = df.drop(columns="species")

In [2]:
print(data.corr())

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [3]:
print(data.iloc[123].max())

6.3

In [4]:
print(data.tail())

     sepal_length  sepal_width  petal_length  petal_width
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [5]:
print(data.shape)

(150, 4)

In [6]:
print(data.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
df2 = pd.read_csv("dataset.zip")
df2.head()

         BMI Gender    Height          W    Stroke
0  24.686513      F  1.923557  96.135290  Positive
1  23.295553      M  1.693292  84.394120  Positive
2  24.575844      F  1.548579  55.617729  Positive
3  24.374107      M  1.837546  61.575890  Positive
4  23.118654      F  1.748800  88.240890  Positive

In [8]:
df2 = df2.rename(columns= {'W': 'Weight'})
df2.head()

         BMI Gender    Height     Weight    Stroke
0  24.686513      F  1.923557  96.135290  Positive
1  23.295553      M  1.693292  84.394120  Positive
2  24.575844      F  1.548579  55.617729  Positive
3  24.374107      M  1.837546  61.575890  Positive
4  23.118654      F  1.748800  88.240890  Positive

In [10]:
df2=df2.fillna({"BMI": df2['BMI'].mean()})
df2['BMI'].isnull().sum()

0

In [11]:
df2=df2.fillna({"Weight": 60})
df2['Weight'].isnull().sum()

0

In [16]:
df2['Stroke'] = df2['Stroke'].replace({'Negative':0, 'Positive':1})
df2['Stroke'].isnull().sum()
df2['Stroke'].unique()

array([1, 0, '#VALUE!'], dtype=object)

In [17]:
df2['Stroke'] = df2['Stroke'].replace({'#VALUE!':1})
df2['Stroke'].unique()

array([1, 0])

In [21]:
df2.dropna(subset=["Height"], inplace=True)
df2.shape

(99, 5)

In [23]:
df2.to_csv(f'processed_dataset.zip', compression=dict(method='zip', archive_name=f'processed_dataset.csv'), encoding='utf-8', index=False, header=True)

In [25]:
df3= pd.read_csv("processed_dataset.zip")
df3.describe()

             BMI     Height     Weight     Stroke
count  99.000000  99.000000  99.000000  99.000000
mean   21.426012   1.754520  75.936424   0.212121
std     1.724714   0.150697  14.726357   0.410891
min    18.507034   1.506391  50.038119   0.000000
25%    20.131459   1.621192  63.813554   0.000000
50%    21.288110   1.751888  76.093768   0.000000
75%    22.539662   1.887671  87.655427   0.000000
max    24.870572   1.999561  99.979522   1.000000

In [35]:
df3.groupby(['Gender']).mean()

              BMI    Height     Weight    Stroke
Gender
F       21.305996  1.734898  76.710821  0.160000
M       21.548478  1.774542  75.146222  0.265306

In [44]:
df3[['BMI','Stroke']].iloc[10:16]

          BMI  Stroke
10  22.239327       0
11  21.474176       0
12  22.164770       0
13  18.757837       0
14  21.722535       0
15  18.840924       0